/**
 * UI API of the NanoForge editor for plugins: widgets and screens, menus, toolbar, status bar,
 * keybindings, notifications, prompts, styles, themes and the component kit.
 *
 * Like the rest of the SDK, the editor provides this module at runtime: plugin widgets use the
 * editor's own components and services.
 */
export {
  FILE_ACTIONS,
  FILE_DECORATIONS,
  FILE_ICONS,
  FILE_TEMPLATES,
  type FileAction,
  type FileDecoration,
  type FileDecorationProvider,
  type FileIcon,
  type FileTemplate,
  type TemplateFile,
  CODE_EDITOR_ACTIVE_FILE,
  CODE_EDITOR_SIDE_PANELS,
  type CodeEditorSidePanel,
  SCENE_EDITORS,
  type SceneEditor,
  VIEWPORT_OVERLAYS,
  VIEWPORT_TOOLS,
  type ViewportOverlay,
  type ViewportScreen,
  type ViewportTool,
  KEYBINDINGS,
  type Keybinding,
  KeybindingSchema,
  MENU_BAR,
  MENU_ITEMS,
  type MenuBarEntry,
  type MenuItem,
  MenuItemSchema,
  type MountedWidget,
  STATUS_BAR_ITEMS,
  type StatusBarItem,
  TOOLBAR_ITEMS,
  type ToolbarItem,
  WIDGETS,
  WIDGET_VIEWS,
  type WidgetDescriptor,
  WidgetDescriptorSchema,
  type WidgetInstance,
  type WidgetView,
  SETTINGS_PAGES,
  type SettingsPage,
  type SettingsPageApi,
  type EditorAction,
  actionId,
  actionLabel,
  isActionEnabled,
  listActions,
  DEFAULT_KEYMAP_PRESET,
  KEYMAP_PRESETS,
  type KeybindingConflict,
  type KeymapOverride,
  type KeymapPreset,
  type ResolvedKeybinding,
  type KeymapLayers,
  type ShortcutRef,
  bindingsConflict,
  findConflicts,
  isActionChanged,
  resetAction,
  resolveLayers,
  setShortcut,
  formatKeybinding,
  parseKeybinding,
  portableStroke,
  resolveKeymap,
  strokeFromEvent,
  type KeybindingService,
  KeybindingServiceToken,
  type LayoutController,
  LayoutControllerToken,
  type NotificationService,
  NotificationServiceToken,
  type PromptService,
  PromptServiceToken,
  type StyleService,
  StyleServiceToken,
  type ThemeDefinition,
  type ThemeService,
  ThemeServiceToken,
  THEMES,
  type WorkbenchService,
  WorkbenchServiceToken,
  registerIcons,
  resolveIcon,
  Button,
  Checkbox,
  ColorPicker,
  Combobox,
  ContextMenu,
  Dialog,
  EmptyState,
  Icon,
  IconButton,
  Input,
  Menu,
  type MenuEntry,
  NumberInput,
  PropertyGrid,
  type PropertyField,
  Select,
  Splitter,
  Switch,
  Tabs,
  Tooltip,
  Tree,
  type DropPosition,
  type TreeNode,
  Vector2Input,
} from '@nanoforge-dev/editor-ui';
