/**
 * DRAFT (2026-09-27) of the schema behind ADR 0003. Field-level details may change.
 *
 * Every value the editor accepts or writes for items (components, systems, and anything a plugin
 * describes): the package manifest, the TSDoc in the sources, and the generated meta.
 *
 * The same pattern at every level:
 *  - core fields, understood by the editor with no plugin;
 *  - `requires`: the npm libs needed to use it;
 *  - owner objects: one key per owner plugin, named after the plugin in our registry
 *    (`"@nanoforge/ecs": {...}`). Only that plugin parses it. Core fields never contain a `/`, so an
 *    owner key can't clash with them.
 *
 * Where each part comes from:
 *  1. `nanoforge.manifest.json`: written by the package author.
 *  2. TSDoc in the `.ts` sources: written by the author. The only source of truth for the docs.
 *  3. The meta: generated by the editor into its cache, never published, never written next to the
 *     sources. Generated at init when missing, regenerated when stale.
 */
import { z } from 'zod';

// ─── Shared ──────────────────────────────────────────────────────────────────────────────────

/** A package in our registry: `@scope/name`. Also the name of an owner plugin. */
export const RegistryName = z.string().regex(/^@[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*$/);

/** An npm package: `@scope/name` or `name`. */
export const NpmName = z.string().regex(/^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/);

/** An export of an npm lib: `@nanoforge-dev/graphics-2d#Rect`. */
export const LibExportRef = z.string().regex(/^[^#\s]+#[A-Za-z_$][\w$]*$/);

/**
 * An item:
 *  - `@nanoforge/motion#Position`: in a package (`nf_modules` or the project's own);
 *  - `app:client#Paddle`: in one of the project's apps (`apps/client`), which has no registry name.
 */
export const ItemRef = z.string().regex(/^(@[a-z0-9-]+\/[a-z0-9-]+|app:[\w.-]+)#[A-Za-z_$][\w$]*$/);

/** A path relative to the manifest (or app root), inside it. */
export const RelativePath = z
  .string()
  .min(1)
  .refine((path) => !path.startsWith('/') && !path.split('/').includes('..'));

/** Where an item runs. A NanoForge app concept (client and server apps), so it's core. */
export const Side = z.enum(['client', 'server', 'shared']);

/**
 * Adds owner objects to a core object: any extra key must be a registry name, and its value is an
 * object only that owner parses. The core keeps it untouched.
 */
const withOwners = <Shape extends z.ZodRawShape>(shape: Shape) =>
  z
    .object(shape)
    .catchall(z.record(z.string(), z.unknown()))
    .superRefine((value, ctx) => {
      for (const key of Object.keys(value)) {
        if (key in shape) continue;
        if (!RegistryName.safeParse(key).success)
          ctx.addIssue({
            code: 'custom',
            path: [key],
            message: 'unknown field: owner keys are registry names ("@scope/name")',
          });
      }
    });

// ─── 1. Package manifest (nanoforge.manifest.json) ──────────────────────────────────────────

/**
 * `type: "package"`: holds items and/or includes sub-packages. It replaces the CLI's
 * `component` / `system` / `bundle` types. A package never holds a plugin: `plugin` keeps its own
 * schema and is installed apart (`~/.nanoforge/editor/plugins` or `<project>/.nanoforge/plugins`)
 * (`packages/kernel/src/plugin/manifest.ts`), plus the `contributes.itemOwner` below.
 */
export const PackageManifest = withOwners({
  $schema: z.string().optional(),
  type: z.literal('package'),
  name: RegistryName,
  version: z.string(), // semver
  description: z.string().optional(),
  tags: z.array(z.string()).default([]),

  /** Other packages of our registry, by name or with a range. */
  dependencies: z.union([z.array(RegistryName), z.record(RegistryName, z.string())]).optional(),
  /** NanoForge engine libs (npm), with a range: `{ "@nanoforge-dev/ecs": "^1.0.0" }`. */
  libDependencies: z.record(NpmName, z.string()).optional(),
  /** Other npm dependencies of the sources. */
  npmDependencies: z.record(NpmName, z.string()).optional(),

  /** Source files whose exports are candidates for items. */
  items: z.array(RelativePath).default([]),
  /** Sub-folders holding their own `package` manifest (never a plugin). Max 4 levels deep. */
  include: z.array(RelativePath).default([]),
  /** Editor plugins that make this package easier to use. The editor names the missing ones. */
  suggestedPlugins: z.union([z.array(RegistryName), z.record(RegistryName, z.string())]).optional(),

  publish: z.object({ paths: z.object({ package: z.string().optional() }).optional() }).optional(),
});
// Owner keys on a manifest: package-level data for that plugin (none in the example).

/** Added to the `plugin` manifest: declares the plugin as an owner. */
export const ItemOwnerContribution = z.object({
  /** Version of the owner object's shape. A change regenerates the metas that hold it. */
  schema: z.number().int().positive(),
  /** The owner tags it claims (without `@`). Lets the editor say which plugin to install. */
  tags: z.array(z.string().regex(/^[a-z][A-Za-z0-9]*$/)),
});
// e.g. @nanoforge/ecs: "contributes": { "itemOwner": { "schema": 1, "tags": ["component", "system", "query", "uses"] } }
// Its `entry.worker` registers the `extract` function (see "Extraction" at the end).

// ─── 2. TSDoc in the sources ─────────────────────────────────────────────────────────────────

/**
 * Where a tag may appear:
 *  - `item`: the doc comment of an exported class, function or const;
 *  - `constructor`: the doc comment of a class constructor (or the function itself for `@param`);
 *  - `field`: the doc comment of a public class field;
 *  - `param`: the inline doc of one constructor parameter (`/** … *\/ public x = 0`).
 */
export type TagPlace = 'item' | 'constructor' | 'field' | 'param';

export type TagSpec = {
  on: TagPlace[];
  /** How the text after the tag is read. */
  syntax: string;
  /** What it becomes in the meta. */
  gives: string;
};

/** Core tags: read by the core extractor, whatever plugins are installed. */
export const CORE_TAGS = {
  '(summary)': {
    on: ['item', 'field'],
    syntax: 'the text before the first tag',
    gives: 'description',
  },
  '@remarks': { on: ['item'], syntax: 'text', gives: 'appended to description' },
  '@param': {
    on: ['constructor'],
    syntax: '@param <name> - <text>',
    gives: 'params[name].description',
  },
  '@example': {
    on: ['item'],
    syntax: 'text or a ```ts fenced block (the fence is stripped)',
    gives: 'example',
  },
  '@side': {
    on: ['item'],
    syntax: '@side client | server | shared',
    gives: 'side (default "shared")',
  },
  '@asset': {
    on: ['constructor', 'field'],
    syntax: 'constructor: @asset <param> [.ext …]; field: @asset [.ext …]',
    gives: 'turns a string element into { type: "asset", accept }',
  },
  '@deprecated': { on: ['item', 'field'], syntax: 'text', gives: 'deprecated' },
  '@internal': {
    on: ['item', 'field'],
    syntax: 'no text',
    gives: 'the export or field is left out of the meta',
  },
  '(param summary)': {
    on: ['param'],
    syntax: 'the inline doc text of the parameter (wins over @param)',
    gives: 'params[name].description, shown behind an ⓘ',
  },

  // Layout: how params look in the inspector (docs/specs/ecs.md, "Param layout").
  '@group (declare)': {
    on: ['item'],
    syntax: '@group <Name> [color=<css color>] [hidden] - <description>',
    gives: 'groups[]: a collapsible section with a colored name and an ⓘ',
  },
  '@group (join)': {
    on: ['param', 'field'],
    syntax: '@group <Name>',
    gives: 'layout.group (an undeclared group is created without description)',
  },
  '@preset': {
    on: ['param', 'field'],
    syntax: '@preset <preset>.<slot> (e.g. vector.x) | @preset <preset> (e.g. color)',
    gives: 'layout.preset: the group params sharing a preset show as one control',
  },
  '@label': { on: ['param', 'field'], syntax: '@label <text>', gives: 'layout.label' },
  '@color': { on: ['param', 'field'], syntax: '@color <css color>', gives: 'layout.color' },
  '@hidden': {
    on: ['param', 'field'],
    syntax: 'no text',
    gives: 'layout.hidden: shown only once chosen in the component\'s "Show hidden" menu',
  },
} satisfies Record<string, TagSpec>;

/**
 * Owner tags: declared by an owner plugin (`contributes.itemOwner.tags`). Only that plugin reads
 * them. Two installed plugins claiming the same tag is an error naming both.
 *
 * A tag that no installed plugin claims is kept raw in `unclaimedTags`, and gives a warning. If the
 * plugin that wrote an owner object is gone when the meta is regenerated, that object isn't
 * generated: it disappears, and its tags go to `unclaimedTags`.
 *
 * Example: the tags @nanoforge/ecs declares.
 */
export const ECS_TAGS = {
  '@component': {
    on: ['item'],
    syntax: 'no text, on a class',
    gives: '"@nanoforge/ecs": { type: "component" }',
  },
  '@system': {
    on: ['item'],
    syntax: 'no text, on a function',
    gives: '"@nanoforge/ecs": { type: "system" }',
  },
  '@query': {
    on: ['item'],
    syntax: '@query <Export> <Export> … (one tag per query); override when not inferable',
    gives: 'query',
  },
  '@uses': {
    on: ['item'],
    syntax: '@uses <ctx lib> …; override when not inferable',
    gives: 'uses',
  },
} satisfies Record<string, TagSpec>;

/**
 * Inferred from the code, not written as tags:
 *  - core: each parameter's and field's type (TypeScript), default (initializer), optional (`?` or a
 *    default), `enum` (string literal union), `enumRef` (a param typed with an exported enum), `ref`
 *    (a param typed with an exported class of an npm lib), `requires` (the npm libs imported);
 *  - @nanoforge/ecs: `name` (the class's `name = "X"` field), a system's `query` (each
 *    `registry.getZipper([...])`) and `uses` (each `ctx.<lib>`).
 *
 * An export becomes an item when it is in a file listed in the manifest's `items`, or, in the
 * project's apps, when an owner tag is on it. Not `@internal`.
 */

// ─── 3. Meta (editor cache) ──────────────────────────────────────────────────────────────────

/** A CSS color, as written in the tag (`orange`, `#4aa3ff`, `rgb(…)`). */
const CssColor = z.string().min(1);

/** How a param or field looks in the inspector. Every field is optional. */
export const ElementLayout = z.object({
  /** Name shown instead of the param name. */
  label: z.string().optional(),
  /** The group it belongs to (`ItemMeta.groups[].name`). */
  group: z.string().optional(),
  /** A visual preset, and the slot it fills: `{ id: "vector", slot: "x" }`, `{ id: "color" }`. */
  preset: z.object({ id: z.string(), slot: z.string().optional() }).optional(),
  /** Color of its name. */
  color: CssColor.optional(),
  /** Hidden until the user chooses it in the component's "Show hidden" menu. */
  hidden: z.boolean().optional(),
});
export type ElementLayout = z.output<typeof ElementLayout>;

/** A group of params, declared in the item's header (`@group Coords color=… hidden - …`). */
export const ParamGroup = z.object({
  name: z.string(),
  description: z.string().optional(),
  color: CssColor.optional(),
  hidden: z.boolean().optional(),
});

/** Common fields of every element (a parameter, a field, an array item, an object property). */
const elementBase = {
  name: z.string(),
  description: z.string().optional(),
  optional: z.boolean().optional(), // default false; true when a default exists
  deprecated: z.string().optional(),
  layout: ElementLayout.optional(),
};

/**
 * A value's type. Core types describe TypeScript, not a lib. Owner objects are allowed on each
 * element (e.g. inspector hints from a plugin).
 *
 * `default`: a JSON value when the initializer is a literal (an enum member gives its value).
 * `defaultCode`: the initializer's source text when it isn't (`new Rect({ width: 10 })`).
 */
export type Element =
  | ({ type: 'string'; default?: string; enum?: string[]; enumRef?: string } & ElementCommon)
  | ({ type: 'number'; default?: number } & ElementCommon)
  | ({ type: 'boolean'; default?: boolean } & ElementCommon)
  | ({ type: 'asset'; default?: string; accept?: string[] } & ElementCommon)
  | ({ type: 'array'; items: Element; default?: unknown[] } & ElementCommon)
  | ({ type: 'object'; properties: Element[]; default?: Record<string, unknown> } & ElementCommon)
  | ({ type: 'ref'; ref: string } & ElementCommon)
  | ({ type: 'unknown'; tsType: string } & ElementCommon);

type ElementCommon = {
  name: string;
  description?: string;
  optional?: boolean;
  deprecated?: string;
  layout?: ElementLayout;
  defaultCode?: string;
  [owner: `${string}/${string}`]: Record<string, unknown>;
};

export const Element: z.ZodType<Element> = z.lazy(() =>
  z.union([
    withOwners({
      ...elementBase,
      type: z.literal('string'),
      default: z.string().optional(),
      defaultCode: z.string().optional(),
      /** Allowed values, from a string literal union (`"left" | "right"`). */
      enum: z.array(z.string()).optional(),
      /** Values come from an exported enum: `@nanoforge-dev/input#InputEnum`. */
      enumRef: LibExportRef.optional(),
    }),
    withOwners({
      ...elementBase,
      type: z.literal('number'),
      default: z.number().optional(),
      defaultCode: z.string().optional(),
    }),
    withOwners({
      ...elementBase,
      type: z.literal('boolean'),
      default: z.boolean().optional(),
      defaultCode: z.string().optional(),
    }),
    withOwners({
      ...elementBase,
      /** A project asset, stored as its path. A string marked with `@asset`. */
      type: z.literal('asset'),
      default: z.string().optional(),
      defaultCode: z.string().optional(),
      /** Accepted extensions (`.png`); any file when absent. */
      accept: z.array(z.string().regex(/^\.[\w.]+$/)).optional(),
    }),
    withOwners({
      ...elementBase,
      type: z.literal('array'),
      items: Element,
      default: z.array(z.unknown()).optional(),
      defaultCode: z.string().optional(),
    }),
    withOwners({
      ...elementBase,
      /** An inline object type (`{ w: number; h: number }`). */
      type: z.literal('object'),
      properties: z.array(Element),
      default: z.record(z.string(), z.unknown()).optional(),
      defaultCode: z.string().optional(),
    }),
    withOwners({
      ...elementBase,
      /** An exported class of an npm lib: `@nanoforge-dev/graphics-2d#Rect`. Edited by the plugin
       *  that contributes an editor for that ref; shown as code otherwise. */
      type: z.literal('ref'),
      ref: LibExportRef,
      defaultCode: z.string().optional(),
    }),
    withOwners({
      ...elementBase,
      /** Anything else (unions of objects, generics…): shown and edited as code. */
      type: z.literal('unknown'),
      tsType: z.string(),
      defaultCode: z.string().optional(),
    }),
  ]),
) as z.ZodType<Element>;

export const ItemMeta = withOwners({
  export: z.string(),
  /** Relative to the manifest (or the app root). */
  source: RelativePath,
  kind: z.enum(['class', 'function', 'const']),
  side: Side,
  description: z.string().optional(),
  example: z.string().optional(),
  deprecated: z.string().optional(),
  /** Constructor parameters (class) or parameters (function), in order, minus claimed ones. */
  params: z.array(Element),
  /** Public fields not set from the constructor, minus claimed ones. */
  fields: z.array(Element).default([]),
  /** Param groups declared in the header, in declaration order, then the undeclared ones used. */
  groups: z.array(ParamGroup).default([]),
  /** npm libs the item's source imports (type-only imports included). */
  requires: z.array(NpmName).default([]),
  /** Tags no installed owner claimed, kept raw: `{ "component": [""], "query": ["A B"] }`. */
  unclaimedTags: z.record(z.string(), z.array(z.string())).optional(),
});
// Owner keys on an item: e.g. "@nanoforge/ecs": EcsItem (below).

/**
 * One meta file per source: a package (from `nf_modules` or the project) or an app.
 * Stored in `.nanoforge/editor/cache/meta/`:
 *  - `modules/@<scope>/<name>.json` for a package in `nf_modules`
 *  - `packages/@<scope>/<name>.json` for a package the project owns
 *  - `apps/<app>.json`              for an app (`apps/<app>`)
 *
 * Regenerated when any of these differ from the stored values: `metaVersion`, `generator.version`,
 * `sourceHash`, or the installed owners (added, removed, other `version` or `schema`).
 */
export const MetaFile = z.object({
  generated: z.literal('Generated by the NanoForge editor. Do not edit.'),
  metaVersion: z.literal(1),
  /** The package that holds the extraction logic (split out, runnable without the editor UI). */
  generator: z.object({ name: z.string(), version: z.string() }),
  source: z.discriminatedUnion('kind', [
    z.object({
      kind: z.literal('module'),
      name: RegistryName,
      version: z.string(),
      path: z.string(),
    }),
    z.object({
      kind: z.literal('package'),
      name: RegistryName,
      version: z.string(),
      path: z.string(),
    }),
    z.object({ kind: z.literal('app'), name: z.string(), path: z.string() }),
  ]),
  /** sha256 over the manifest and each listed source (path, NUL, bytes, NUL), in `items` order. */
  sourceHash: z.string().regex(/^sha256-[0-9a-f]{64}$/),
  /** The owner plugins that ran, and what they wrote with. */
  owners: z.record(RegistryName, z.object({ version: z.string(), schema: z.number().int() })),
  items: z.array(ItemMeta),
});

// ─── Example owner: @nanoforge/ecs ────────────────────────────────────────────────────────────
// Owned and validated by the plugin, not by core. Shown here to see a full item.

export const EcsItem = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('component'),
    /** The registry key: the class's `name = "X"` field. Claimed, so not in `fields`. */
    name: z.string(),
  }),
  z.object({
    type: z.literal('system'),
    /** One list per `registry.getZipper([...])`. The `(registry, ctx)` params are claimed. */
    query: z.array(z.array(ItemRef)),
    /** `ctx` libs it uses: app, graphics, input, network… */
    uses: z.array(z.string()),
  }),
]);

// ─── Extraction (for the split package) ──────────────────────────────────────────────────────

/**
 * What an owner registers in the worker. The core extractor calls `extract` for every candidate
 * export (with its raw tags and the TypeScript declaration) and stores the result under the owner's
 * key, after validating it with `schema`.
 */
export type ItemOwner = {
  name: string; // the plugin's registry name = the owner key
  schema: number;
  tags: string[];
  /** Members it claims: left out of `params` / `fields`. */
  claims?: (declaration: unknown) => { params?: string[]; fields?: string[] };
  extract: (input: {
    declaration: unknown; // ts-morph node
    tags: Record<string, string[]>; // this owner's tags on the item
  }) => Record<string, unknown> | undefined; // undefined: not an item for this owner
  validate: z.ZodType;
};
