export * from './widget.extension-point';
export * from './menu.extension-point';
export * from './status-bar.extension-point';
export * from './keybinding.extension-point';
export * from './toolbar.extension-point';
export * from './file.extension-point';
export * from './code-editor.extension-point';
export * from './viewport.extension-point';
export * from './settings-page.extension-point';
