export const exampleLogs = [
  {
    id: 1,
    time: '09:58:02.011',
    level: 'info',
    source: 'NanoForge',
    message: 'Starting NanoForge Editor v0.6.0 (Web)',
  },
  {
    id: 2,
    time: '09:58:02.028',
    level: 'info',
    source: 'Runtime',
    message: 'Browser runtime detected: Chrome 121 (WASM + WebGPU)',
  },
  {
    id: 3,
    time: '09:58:02.061',
    level: 'info',
    source: 'Memory',
    message: 'Heap initialized (256 MB)',
  },
  {
    id: 4,
    time: '09:58:02.114',
    level: 'info',
    source: 'Project',
    message: "Opening project 'JumpOut'",
  },
  {
    id: 5,
    time: '09:58:02.147',
    level: 'info',
    source: 'Project',
    message: 'Project config loaded',
  },
  {
    id: 6,
    time: '09:58:02.201',
    level: 'info',
    source: 'ECS',
    message: 'Creating ECS World',
  },
  {
    id: 7,
    time: '09:58:02.224',
    level: 'info',
    source: 'ECS',
    message: 'Registered 14 components',
  },
  {
    id: 8,
    time: '09:58:02.242',
    level: 'info',
    source: 'ECS',
    message: 'Archetype cache initialized',
  },
  {
    id: 9,
    time: '09:58:02.267',
    level: 'info',
    source: 'Component',
    message: 'Component registered: Transform',
  },
  {
    id: 10,
    time: '09:58:02.268',
    level: 'info',
    source: 'Component',
    message: 'Component registered: Velocity',
  },
  {
    id: 11,
    time: '09:58:02.270',
    level: 'info',
    source: 'Component',
    message: 'Component registered: Sprite',
  },
  {
    id: 12,
    time: '09:58:02.273',
    level: 'info',
    source: 'Component',
    message: 'Component registered: Collider',
  },
  {
    id: 13,
    time: '09:58:02.312',
    level: 'info',
    source: 'System',
    message: 'System loaded: TransformSystem',
  },
  {
    id: 14,
    time: '09:58:02.325',
    level: 'info',
    source: 'System',
    message: 'System loaded: PhysicsSystem',
  },
  {
    id: 15,
    time: '09:58:02.339',
    level: 'info',
    source: 'System',
    message: 'System loaded: RenderSystem',
  },
  {
    id: 16,
    time: '09:58:02.354',
    level: 'info',
    source: 'System',
    message: 'System loaded: InputSystem',
  },
  {
    id: 17,
    time: '09:58:02.389',
    level: 'info',
    source: 'Scheduler',
    message: 'ECS scheduler initialized (fixed update: 60Hz)',
  },
  {
    id: 18,
    time: '09:58:02.401',
    level: 'warning',
    source: 'Scheduler',
    message: "System 'PhysicsSystem' exceeds frame budget (3.2ms)",
  },
  {
    id: 19,
    time: '09:58:02.447',
    level: 'info',
    source: 'Assets',
    message: 'Importing assets',
  },
  {
    id: 20,
    time: '09:58:02.491',
    level: 'info',
    source: 'Assets',
    message: 'Texture loaded: ship.png (512x512)',
  },
  {
    id: 21,
    time: '09:58:02.522',
    level: 'info',
    source: 'Assets',
    message: 'Shader compiled: sprite.wgsl',
  },
  {
    id: 22,
    time: '09:58:02.581',
    level: 'info',
    source: 'Scene',
    message: 'Spawning entities',
  },
  {
    id: 23,
    time: '09:58:02.602',
    level: 'info',
    source: 'ECS',
    message: 'Entity created: id=42 (Transform, Velocity, Sprite)',
  },
  {
    id: 24,
    time: '09:58:02.618',
    level: 'info',
    source: 'ECS',
    message: 'Entity created: id=43 (Transform, Collider)',
  },
  {
    id: 25,
    time: '09:58:02.689',
    level: 'info',
    source: 'Runtime',
    message: 'Entering Play Mode',
  },
  {
    id: 26,
    time: '09:58:03.012',
    level: 'info',
    source: 'Runtime',
    message: 'Frame time: 16.4ms (61 FPS)',
  },
  {
    id: 27,
    time: '09:58:03.219',
    level: 'warning',
    source: 'PhysicsSystem',
    message: 'Entity 43 has Collider but no Rigidbody',
  },
  {
    id: 28,
    time: '09:58:03.401',
    level: 'error',
    source: 'RenderSystem',
    message: "Failed to bind texture 'asteroid.png' (not loaded)",
  },
  {
    id: 29,
    time: '09:58:03.402',
    level: 'error',
    source: 'Runtime',
    message: 'Frame aborted due to previous error',
  },
  {
    id: 30,
    time: '09:58:03.435',
    level: 'info',
    source: 'Editor',
    message: 'Play Mode paused',
  },
];
