import { z } from 'zod';

import { Element, ItemKindSchema, ParamGroup } from './element.schema';
import { NpmName, RegistryName, Side } from './item-ref.schema';
import { withOwners } from './owner-object';

export const ItemMeta = withOwners({
  export: z.string(),
  /** Project path of the source file. */
  source: z.string(),
  kind: ItemKindSchema,
  side: Side,
  description: z.string().optional(),
  example: z.string().optional(),
  deprecated: z.string().optional(),
  /** Constructor parameters (class) or parameters (function), in order, minus claimed ones. */
  params: z.array(Element),
  /** Public fields not set from the constructor, minus claimed ones. */
  fields: z.array(Element).default([]),
  /** Param groups declared in the header, in declaration order, then undeclared ones used. */
  groups: z.array(ParamGroup).default([]),
  /** npm packages the item's source imports (type-only imports included). */
  requires: z.array(NpmName).default([]),
  /** Tags no installed owner claimed, kept raw: `{ "component": [""], "query": ["A B"] }`. */
  unclaimedTags: z.record(z.string(), z.array(z.string())).optional(),
});
export type ItemMeta = z.output<typeof ItemMeta>;

/**
 * Where items come from:
 *  - `module`: an installed package (`nf_modules/@scope/name`), read-only;
 *  - `lib`: a shared library of the project (`libs/<folder>`, ADR 0004);
 *  - `app`: an app of the project (`apps/client`).
 */
export const MetaSource = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('module'),
    name: RegistryName,
    version: z.string(),
    path: z.string(),
  }),
  z.object({ kind: z.literal('lib'), name: NpmName, path: z.string() }),
  z.object({ kind: z.literal('app'), name: z.string(), path: z.string() }),
]);
export type MetaSource = z.output<typeof MetaSource>;

/** The `<source>` part of the item references of a source. */
export const sourceRefBase = (source: MetaSource): string =>
  source.kind === 'app' ? `app:${source.name}` : source.name;

export const META_VERSION = 1;
export const META_NOTICE = 'Generated by the NanoForge editor. Do not edit.';

/** One cache file per source, in `.nanoforge/editor/cache/meta/`. */
export const MetaFile = z.object({
  generated: z.literal(META_NOTICE),
  metaVersion: z.literal(META_VERSION),
  /** The package that holds the extraction logic. */
  generator: z.object({ name: z.string(), version: z.string() }),
  source: MetaSource,
  /** sha256 over each source file (path, NUL, text, NUL), sorted by path. */
  sourceHash: z.string().regex(/^sha256-[0-9a-f]{64}$/),
  /** The owner plugins that ran, and the schema version of what they wrote. */
  owners: z.record(RegistryName, z.object({ version: z.string(), schema: z.number().int() })),
  items: z.array(ItemMeta),
});
export type MetaFile = z.output<typeof MetaFile>;

/** Cache path of a source's meta, relative to the project root. */
export const metaCachePath = (source: MetaSource): string => {
  const base = '.nanoforge/editor/cache/meta';
  switch (source.kind) {
    case 'module':
      return `${base}/modules/${source.name}.json`;
    case 'lib':
      return `${base}/libs/${source.name}.json`;
    case 'app':
      return `${base}/apps/${source.name}.json`;
  }
};
