name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  ORG_NAME: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  CONFIG_FILE: kubernetes/nanoforge/editor-override.yaml

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NanoForge-dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare
        uses: ./.github/actions/prepare
        env:
          PUBLIC_MODE: ${{ vars.PUBLIC_MODE }}
          PUBLIC_PM_URL: ${{ vars.PUBLIC_PM_URL }}

      - name: Release packages
        uses: ./node_modules/@nanoforge-dev/actions/dist/release-packages
        with:
          package: '@nanoforge-dev/editor'
          dry: ${{ inputs.dry_run }}
          format: '{version}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: ./.github/actions/docker-push
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
          token: ${{ secrets.TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
