name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PUBLIC_MODE: ${{ vars.PUBLIC_MODE }}
  PUBLIC_PM_URL: ${{ vars.PUBLIC_PM_URL }}
  PUBLIC_DOCS_URL: ${{ vars.PUBLIC_DOCS_URL }}
  PUBLIC_LANDING_URL: ${{ vars.PUBLIC_LANDING_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test:unit
